name: 'test'

on:
  workflow_call:

jobs:
  test:
    name: 'Test'
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Capture Yarn cache path
        id: yarn-cache-folder
        run: echo "YARN_CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        if: runner.os != 'Windows'
        with:
          path: ${{ steps.yarn-cache-folder.outputs.YARN_CACHE_FOLDER }}
          key: yarn-cache
      - name: Install dependencies
        run: tool/yarn install --frozen-lockfile --prefer-offline
      - name: Unit tests
        run: tool/yarn test
      - name: Lint
        run: tool/yarn lint
      - name: Typescript
        run: tool/yarn tsc --noEmit
      - name: Prettier
        run: tool/yarn prettier --check .
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Test in SSH environment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /path/to/extension && tool/yarn test'
      - name: Set up Dev Container
        uses: devcontainers/ci@v0
        with:
          image: mcr.microsoft.com/vscode/devcontainers/base:0-focal
      - name: Test in Dev Container
        run: |
          docker exec -w /path/to/extension devcontainer tool/yarn test
      - name: Set up GitHub Codespaces
        uses: actions/checkout@v3
      - name: Test in GitHub Codespaces
        run: |
          codespaces exec -w /path/to/extension tool/yarn test
